dist: trusty
language: ruby
sudo: true # need this for libgirepository1.0-dev
# sudo: false # taking advantage of container-based infrastructure
cache: bundler # cache bundled gems from build to build

addons:
  apt:
    packages:
      - libgirepository1.0-dev # for gobject-introspection

rvm:
  - 2.2
  - 2.3.3
  - 2.4.0-preview3
matrix:
  allow_failures:
    - rvm: 2.4.0-preview3
