language: ruby
sudo: false # taking advantage of container-based infrastructure
cache: bundler # maybe someday they'll add support for us freeloaders...
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
matrix:
  allow_failures:
    - rvm: jruby-head
